//
// Created by realxie on 2019-10-02.
//

#ifndef VULKANDEMO_RHIFLAGS_H
#define VULKANDEMO_RHIFLAGS_H

#include "Macros.h"

NS_RHI_BEGIN

typedef enum BufferUsageFlagBits {
    BUFFER_USAGE_TRANSFER_SRC_BIT = 0x00000001,
    BUFFER_USAGE_TRANSFER_DST_BIT = 0x00000002,
    BUFFER_USAGE_UNIFORM_TEXEL_BUFFER_BIT = 0x00000004,
    BUFFER_USAGE_STORAGE_TEXEL_BUFFER_BIT = 0x00000008,
    BUFFER_USAGE_UNIFORM_BUFFER_BIT = 0x00000010,
    BUFFER_USAGE_STORAGE_BUFFER_BIT = 0x00000020,
    BUFFER_USAGE_INDEX_BUFFER_BIT = 0x00000040,
    BUFFER_USAGE_VERTEX_BUFFER_BIT = 0x00000080,
    BUFFER_USAGE_INDIRECT_BUFFER_BIT = 0x00000100,
    BUFFER_USAGE_CONDITIONAL_RENDERING_BIT_EXT = 0x00000200,
    BUFFER_USAGE_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
} BufferUsageFlagBits;


typedef enum SharingMode {
    SHARING_MODE_EXCLUSIVE = 0,
    SHARING_MODE_CONCURRENT = 1,
    SHARING_MODE_BEGIN_RANGE = SHARING_MODE_EXCLUSIVE,
    SHARING_MODE_END_RANGE = SHARING_MODE_CONCURRENT,
    SHARING_MODE_RANGE_SIZE = (SHARING_MODE_CONCURRENT - SHARING_MODE_EXCLUSIVE + 1),
    SHARING_MODE_MAX_ENUM = 0x7FFFFFFF
} SharingMode;

NS_RHI_END

#endif //VULKANDEMO_RHIFLAGS_H
